import type { Tender } from "./types";

const today = new Date();
const inDays = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString();
};
const daysAgo = (n: number) => inDays(-n);

export const SEED_TENDERS: Tender[] = [
  {
    id: "tzn-it-2026-001",
    title: "IT Services Tender — Tzaneen Municipality",
    source: "etenders",
    link: "https://etenders.gov.za/tzaneen-it-2026",
    municipality: "Tzaneen",
    province: "Limpopo",
    category: "Software Development & Support",
    budgetMin: 800000,
    budgetMax: 1200000,
    deadline: inDays(3),
    datePosted: daysAgo(9),
    status: "preparing",
    fitScore: 87,
    requirements: [
      { text: "React web platform for citizen reporting", fit: "expert", score: 95 },
      { text: "AWS-based cloud hosting & DevOps", fit: "competent", score: 80 },
      { text: "BEE Level 1 certification required", fit: "gap", score: 40 },
      { text: "5-year track record in software delivery", fit: "expert", score: 90 },
    ],
    risks: ["Tight 11-day timeline", "BEE cert renewal pending", "No prior Tzaneen work"],
    recommendation: "Shortlist & prepare bid — strong technical match.",
    checklist: [
      { id: "c1", item: "Tax Clearance Certificate", assignee: "Casious", dueDate: inDays(-1), completed: true },
      { id: "c2", item: "Company profile updated", assignee: "Bokang", dueDate: inDays(0), completed: true },
      { id: "c3", item: "Technical proposal drafted", assignee: "Casious", dueDate: inDays(1), completed: false },
      { id: "c4", item: "Financial bid prepared", assignee: "Bokang", dueDate: inDays(1), completed: false },
      { id: "c5", item: "Compliance checklist signed", assignee: "Casious", dueDate: inDays(2), completed: false },
    ],
    comments: [
      { id: "m1", author: "Casious", text: "Risk on timeline is real. Can we do it?", timestamp: daysAgo(4) },
      { id: "m2", author: "Bokang", text: "Yes, if we prioritise this. Let's do it.", timestamp: daysAgo(3) },
      { id: "m3", author: "Casious", text: "Agreed. Moving to preparing bid.", timestamp: daysAgo(2) },
    ],
  },
  {
    id: "plk-cloud-2026-014",
    title: "Municipal Cloud Migration — Polokwane",
    source: "etenders",
    link: "https://etenders.gov.za/polokwane-cloud",
    municipality: "Polokwane",
    province: "Limpopo",
    category: "Cloud Infrastructure",
    budgetMin: 1500000,
    budgetMax: 2500000,
    deadline: inDays(5),
    datePosted: daysAgo(12),
    status: "submitted",
    fitScore: 92,
    requirements: [
      { text: "Migrate 14 legacy services to AWS", fit: "expert", score: 95 },
      { text: "Zero-downtime cutover plan", fit: "expert", score: 92 },
      { text: "POPIA compliance audit trail", fit: "competent", score: 78 },
    ],
    risks: ["Large scope", "Tight cutover window"],
    recommendation: "Submitted. Strong fit — high win probability.",
    checklist: [
      { id: "c1", item: "Bid pack submitted via portal", assignee: "Bokang", dueDate: daysAgo(2), completed: true },
    ],
    comments: [],
  },
  {
    id: "cogta-gp-2026-022",
    title: "COGTA Citizen Portal Redesign — Gauteng",
    source: "BidLinkssa",
    link: "https://bidlinkssa.co.za/cogta-portal",
    municipality: "Johannesburg",
    province: "Gauteng",
    category: "Software Development & Support",
    budgetMin: 2200000,
    budgetMax: 3500000,
    deadline: inDays(12),
    datePosted: daysAgo(3),
    status: "shortlisted",
    fitScore: 78,
    requirements: [
      { text: "Next.js multilingual portal", fit: "expert", score: 92 },
      { text: "Integration with municipal billing API", fit: "competent", score: 70 },
      { text: "Accessibility WCAG 2.1 AA", fit: "competent", score: 75 },
    ],
    risks: ["Billing API undocumented", "Strong incumbent vendor"],
    recommendation: "Shortlist — schedule technical workshop.",
    checklist: [],
    comments: [
      { id: "m1", author: "Casious", text: "Worth pursuing. Need to scope billing integration.", timestamp: daysAgo(1) },
    ],
  },
  {
    id: "bfn-data-2026-007",
    title: "Data Extraction Platform — Bloemfontein Metro",
    source: "etenders",
    link: "https://etenders.gov.za/bfn-data",
    municipality: "Bloemfontein",
    province: "Free State",
    category: "AI/ML Solutions",
    budgetMin: 600000,
    budgetMax: 900000,
    deadline: inDays(18),
    datePosted: daysAgo(2),
    status: "shortlisted",
    fitScore: 94,
    requirements: [
      { text: "PDF + scanned document extraction", fit: "expert", score: 96 },
      { text: "Pampiri™-style structured output", fit: "expert", score: 98 },
      { text: "On-prem deployment option", fit: "competent", score: 72 },
    ],
    risks: ["On-prem deployment adds 2 weeks"],
    recommendation: "High fit — Pampiri™ direct application.",
    checklist: [],
    comments: [],
  },
  {
    id: "jhb-mobile-2026-031",
    title: "Field Inspector Mobile App — JHB Roads Agency",
    source: "BidLinkssa",
    link: "https://bidlinkssa.co.za/jra-mobile",
    municipality: "Johannesburg",
    province: "Gauteng",
    category: "Mobile Apps",
    budgetMin: 450000,
    budgetMax: 700000,
    deadline: inDays(22),
    datePosted: daysAgo(1),
    status: "identified",
    fitScore: 81,
    requirements: [
      { text: "React Native cross-platform", fit: "expert", score: 90 },
      { text: "Offline-first sync", fit: "competent", score: 78 },
      { text: "Geo-tagged inspection capture", fit: "competent", score: 75 },
    ],
    risks: ["Hardware procurement dependency"],
    recommendation: "Review — solid fit, modest budget.",
    checklist: [],
    comments: [],
  },
  {
    id: "moki-web-2026-044",
    title: "Tourism Website Refresh — Modimolle-Mookgophong",
    source: "etenders",
    link: "https://etenders.gov.za/moki-tourism",
    municipality: "Modimolle",
    province: "Limpopo",
    category: "Web Development",
    budgetMin: 180000,
    budgetMax: 280000,
    deadline: inDays(28),
    datePosted: daysAgo(1),
    status: "identified",
    fitScore: 68,
    requirements: [
      { text: "CMS-driven public website", fit: "expert", score: 92 },
      { text: "Local language content workflow", fit: "competent", score: 65 },
    ],
    risks: ["Low margin", "Heavy content work"],
    recommendation: "Consider for partnership with design studio.",
    checklist: [],
    comments: [],
  },
  {
    id: "gpw-host-2026-019",
    title: "Provincial Hosting & DR — Gauteng Provincial Works",
    source: "etenders",
    link: "https://etenders.gov.za/gpw-hosting",
    municipality: "Pretoria",
    province: "Gauteng",
    category: "Hosting & DevOps",
    budgetMin: 1100000,
    budgetMax: 1800000,
    deadline: inDays(35),
    datePosted: daysAgo(4),
    status: "identified",
    fitScore: 86,
    requirements: [
      { text: "99.95% uptime SLA", fit: "expert", score: 90 },
      { text: "Multi-region DR within RSA", fit: "competent", score: 78 },
    ],
    risks: ["Penalty clauses on uptime"],
    recommendation: "Strong fit — review SLA penalties.",
    checklist: [],
    comments: [],
  },
  {
    id: "nelm-it-2025-088",
    title: "IT Helpdesk Outsourcing — Nelspruit",
    source: "etenders",
    link: "https://etenders.gov.za/nelm-helpdesk",
    municipality: "Nelspruit",
    province: "Gauteng",
    category: "Software Development & Support",
    budgetMin: 700000,
    budgetMax: 900000,
    deadline: daysAgo(30),
    datePosted: daysAgo(80),
    status: "won",
    fitScore: 88,
    requirements: [],
    risks: [],
    recommendation: "Awarded.",
    checklist: [],
    comments: [],
    outcome: { note: "Awarded — 12-month contract. Kickoff next month." },
  },
  {
    id: "lim-edu-2025-061",
    title: "Education Portal — Limpopo Dept of Education",
    source: "etenders",
    link: "https://etenders.gov.za/lim-edu",
    municipality: "Polokwane",
    province: "Limpopo",
    category: "Software Development & Support",
    budgetMin: 1600000,
    budgetMax: 2400000,
    deadline: daysAgo(45),
    datePosted: daysAgo(110),
    status: "lost",
    fitScore: 74,
    requirements: [],
    risks: [],
    recommendation: "Lost on price.",
    checklist: [],
    comments: [],
    outcome: { note: "Lost — incumbent vendor undercut by 22%." },
  },
];
